#!/usr/bin/env bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
        scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi

# Transfer the file using scp with strict host key checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"

# Assign arguments to variables
FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4
